### ISSUE TITLE
SSH Connection issue

### ISSUE THREAD

**Issue by mysth** [wexample/wex#1]
When we type ;

> wex wex/update

If we have placed the certificates files in another folder than usual e.g. `C:/mySSHCertificates` then it will not succeed to pull the data from the repository. This will show these error messages :

> Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> chown: invalid user: ‘root:root’

**Comment by weeger** [comment]
This is a GIT related issue, not wex scripts, however we can create a configuration method :

```bash
wex wex/configure -rsa=/local/path/to/private/rsa
```

Using :

```bash
# Use local private key as deployment key
git config core.sshCommand "ssh -i "${SSH_PRIVATE_KEY}
```
