### ISSUE TITLE
Bad counter

### ISSUE THREAD

**Issue by lperamo** [wexample/wex#11]
When there is actually no dumps, it shows :

> No dump found.
> Choose a db dump (1 to 0) :

"1 to 0" is not correct. Moreover, it does not make any sense to have to choose a db dump if there are no dumps.

**Comment by mysth** [comment]
Maybe we can also indicate where the dumps have to be.
"No dumps found in /my/path/dumps."

**Comment by weeger** [comment]
Solved with new choice selection
