### ISSUE TITLE
Install on OSX

### ISSUE THREAD

**Issue by Joyoyoyoyo** [wexample/wex#15]
- Update bash to version 4
- Use brew instead apt-get
- Check system with ‘wex system/osNew‘ => mac

**Comment by weeger** [comment]
Site install / init / starting is now working (release/v3 branch).

**Comment by Joyoyoyoyo** [comment]
Ça tombe bien je viens de changer de Mac 😂😂

Le lun. 9 sept. 2019 à 10:05, Romain Weeger <notifications@github.com> a
écrit :
