### ISSUE TITLE
Adding a branded grub initialization

### ISSUE THREAD

**Issue by lperamo** [wexample/wex#18]
We should add a grub initialization by editing the `/etc/default/grub` with root access and ensure to have :

```
export GRUB_GFXMODE="1920x1080"
export GRUB_COLOR_NORMAL="red/black"
export GRUB_COLOR_HIGHLIGHT="white/black"
export GRUB_MENU_PICTURE="/boot/grub/grub-logo-v2.png"
export GRUB_FONT="/boot/grub/fonts/unifont-regular-16.pf2"
```

The image dimensions and the `GRUB_GFXMODE` must be at the exact same dimensions.
If we can have one image that we resize to match the user screen, it would be nice.
If we found a better font than unifont for grub, it is perfect but it is difficult to find a font that have no descent glyphs and have a sufficiently high number of glyphs in order that there is no interrogation marks instead of the characters we want to display.
If we put the image in the path i mentioned, we may potentially avoid to add it in the config as Grub will detect it automatically (i have not tested that yet).

When the file is saved, we must do : 
`sudo grub-mkconfig -o /boot/grub/grub.cfg`.

That's all folks !

**Comment by weeger** [comment]
Is the GRUB_FONT required ?

A suggestion of script file for `wex grub/customize`, we may also place this kind on fun stuffs in a specific addon to not mix it up with core features : 

```
#!/usr/bin/env bash

grubCustomizeArgs() {
  _DESCRIPTION="Allow to add a custom image in the grub menu when having a dual boot laptop"
  _ARGUMENTS=(
    'image_path i "Full image path, file should exist" true'
    'color c "Color" true red/black'
    // ...
  )
  # Will prevent to execute method with "sudo", but asks sudo password and run content as sudo.
  _AS_SUDO=false
  _AS_SUDO_RUN=true
}

grubCustomize() {
  # TODO check parameters validity ${IMAGE_PATH}, ${COLOR}, etc...
  # TODO copy image in expected folder
  # TODO Add variables in /etc/default/grub like :
  #            wex file/textAppendOnce -f="/etc/default/grub" -l="export GRUB_GFXMODE=1920x1080"
  #            OR wex config/setValue -f=... -s="=" -k="export GRUB_GFXMOD" -v=1920x108
  # TODO execute : sudo grub-mkconfig -o /boot/grub/grub.cfg
}

**Comment by weeger** [comment]
Postponed
