### ISSUE TITLE
Use iproute2 instead of ifconfig

### ISSUE THREAD

**Issue by weeger** [wexample/wex#30]
@xlii-chl said : The package net-tools and the included ifconfig seems to be slowly abandoned in favor of iproute2.

It should be great to stick to the most commonly used packages.

**Comment by xlii-chl** [comment]
Quick note before going to sleep :)
```sh
ip route get 198.51.100.1 | sed -n 's/.* src \([^[:space:]]*\) .*/\1/p'
ip route get 2001:DB8::1 | sed -n 's/.* src \([^[:space:]]*\) .*/\1/p'
```
Also available in JSON :
```sh
ip -json route get 198.51.100.1
# [{...,"prefsrc":"192.168.0.12",...}]
```
The 198.51.100.0/24 (RFC5737 TEST-NET-2) and 2001:db8::/32 (RFC3849) are reserved addresses so it should be safe to use them as is.

**Comment by weeger** [comment]
What do you think about this ChatGPT version ? 

    ip addr show | awk '/inet /{print $2}' | cut -d'/' -f1 | grep -v '127.0.0.1'

**Comment by xlii-chl** [comment]
Well, if it works on your side, that's good but on mine, it outputs the dockers' adresses:
```
# ip addr show | awk '/inet /{print $2}' | cut -d'/' -f1 | grep -v '127.0.0.1'
192.168.1.12
172.16.238.1
172.18.0.1
172.17.0.1
# ip route get 198.51.100.1 | sed -n 's/.* src \([^[:space:]]*\) .*/\1/p'
192.168.1.12
```

On another computer with some virtualization, the VM network address is before the "main" one:
```
$ ip addr show | awk '/inet /{print $2}' | cut -d'/' -f1 | grep -v '127.0.0.1'
10.0.5.1
192.168.0.27
$ ip route get 198.51.100.1 | sed -n 's/.* src \([^[:space:]]*\) .*/\1/p'
192.168.0.27
```

(note: you can replace `198.51.100.1` by `1.1.1.1` or `8.8.8.8` if you feel it makes more sense.)

**Comment by weeger** [comment]
Seems to work...
