### ISSUE TITLE
(wishlist) Apache: add a volume to allow customization of number of process

### ISSUE THREAD

**Issue by xlii-chl** [wexample/wex#41]
By default, the prefork mode of Apache allows up to 150 process to be launched, which is enough to flood a standard size server (with a PHP process taking ~60MB, it goes up to 9GB). By adding a volume pointing to `/etc/apache2/mods-available/mpm_prefork.conf` or, preferably, a new file like `/etc/apache2/conf-enabled/custom-wex.conf` which is included after `/etc/apache2/mods-enabled/*` in recent Debian/Ubuntu installation, we could overwrite the default values.

Note 1 : a currently available alternative is to write into the virtualhost file, outside of `<VirtualHost>...</VirtualHost>` but it doesn't feel really clean :)

Note 2 : on the PHP side, there seems to already be a way to set the memory_limit via `php/web.dev.ini` for example.

**Comment by weeger** [comment]
Nice ! <3

**Comment by weeger** [comment]
Need to be double checked.

The new PHP container has a volume : 

            - ${CONF_MPM_PREFORK_APACHE_CONF}:/etc/apache2/mods-available/mpm_prefork.conf

Which is containing : 

```
# prefork MPM
# StartServers: number of server processes to start
# MinSpareServers: minimum number of server processes which are kept spare
# MaxSpareServers: maximum number of server processes which are kept spare
# MaxRequestWorkers: maximum number of server processes allowed to start
# MaxConnectionsPerChild: maximum number of requests a server process serves

<IfModule mpm_prefork_module>
        StartServers                     5
        MinSpareServers           5
        MaxSpareServers          10
        # wex : default 150 is overkill for common usages.
        MaxRequestWorkers         150
        # wex : default to 0
        MaxConnectionsPerChild   1024
</IfModule>

**Comment by weeger** [comment]
@xlii-chl I forgot the good value for MaxRequestWorkers, T_T

**Comment by xlii-chl** [comment]
Memo : this issue may be obsoleted by the work done on php-fpm : https://github.com/wexample/wex-addon-services-php/pull/1

**Comment by weeger** [comment]
Why remove libapache2-mod-php instead of just not installing it in php-common image ?

**Comment by weeger** [comment]
Fixed with php-fpm, so we can remove the mpm_prefork.conf file ?

**Comment by xlii-chl** [comment]
Yes, `mpm_prefork.conf` is not used anymore and might hinder some scripts.
But maybe replace it by some generic include to be able to override some Apache configuration outside of the `<Virtualhost>` blocks.

**Comment by weeger** [comment]
Removed
