### ISSUE TITLE
nginx/proxy : big logs

### ISSUE THREAD

**Issue by xlii-chl** [wexample/wex#42]
The wex_server_prod docker writes continuously to `/opt/wex_server/proxy/logs/access.log` which could result in some big and unmanageable file, and even disk space saturation.

Among the solutions:
* add a cron to rotate the logs (`logrotate` for example),
* maybe reuse Docker logging system (not tested).

**Comment by weeger** [comment]
Is just disabling logs might be a solution ? 

![image](https://user-images.githubusercontent.com/1240307/216003467-2a130f37-4174-4b87-ad33-df6acdde5487.png)

Personally, I probably used logs two or three times in years, with no relevant information for debugging.

**Comment by xlii-chl** [comment]
Yes, disabling logs could be a solution (don't forget also the less verbose `error_log`) but logs can be useful, even in production environments.

Reusing the docker logs could be achieved like that (quickly tested) :
```
# inject the error log to the stderr stream of the container's main process
error_log  /proc/1/fd/2 warn;

[...]

   # inject error log to the stdout stream of the container's main process
   access_log /proc/1/fd/1 vhost;
```

**Comment by weeger** [comment]
Done
